# Generated by Django 2.2.23 on 2021-05-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='is_excluded',
        ),
    ]
