# Generated by Django 2.2.23 on 2021-06-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reversi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='points',
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='state',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app_reversi.GamePlayer'),
        ),
    ]
