# Generated by Django 2.2.23 on 2021-06-06 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reversi', '0002_auto_20210605_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='is_active',
            new_name='use_image',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='is_passing',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='is_winner',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='active_player_idx',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='state',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
    ]
