# Generated by Django 2.2.23 on 2021-06-06 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reversi', '0003_auto_20210606_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='winner_player_idx',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
